#!/usr/bin/env bash
name=$1
MyTree="$name at $(date)"

mkdir "$MyTree"

cd "$MyTree"

mkdir -p {about_me/{personal,professional},my_friends,my_system_info}

touch about_me/personal/facebook.txt
touch about_me/professional/linkedin.txt
touch my_friends/list_of_my_friends.txt
touch my_system_info/{about_this_laptop.txt,internet_connection.txt}

echo "https://www.facebook.com/in/$2" >> about_me/personal/facebook.txt
echo "https://www.linkedin.com/in/$3" >> about_me/professional/linkedin.txt


curl https://gist.githubusercontent.com/tegarimansyah/e91f335753ab2c7fb12815779677e914/raw/4588cdc062b6fd44847ad2f9bc1fe9bb547dbeca/list_of_my_friends.txt >> my_friends/list_of_my_friends.txt


echo "My Username: $4" >> my_system_info/about_this_laptop.txt
echo "My host: " $(uname -a) >> my_system_info/about_this_laptop.txt


echo "Connection to google: "  >> my_system_info/internet_connection.txt
ping -c 3 google.com  >> my_system_info/internet_connection.txt
